org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# تعطيل الميزات الجديدة مؤقتاً لتتوافق مع مكتبات Flutter الحالية
android.newDsl=false
android.builtInKotlin=false

# تعطيل وضع R8 الصارم لمنع مشاكل Dexing التالفة في المكتبات الفرعية
android.enableR8.fullMode=false